docRoot                   $VH_ROOT/html/public/
enableGzip                1

index  {
  useServer               0
  indexFiles              index.php
  autoIndex               0
}

errorlog $VH_ROOT/logs/error.log {
  useServer               1
  logLevel                WARN
  rollingSize             10M
}

accesslog $VH_ROOT/logs/access.log {
  useServer               0
  logFormat               "%h %l %u %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-Agent}i\""
  logHeaders              5
  rollingSize             10M
  keepDays                7
}

context / {
  location                $DOC_ROOT/
  allowBrowse             1
  rewrite  {
    RewriteFile           .htaccess
  }
}

rewrite  {
  enable                  1
  autoLoadHtaccess        1
  logLevel                0
}

accessControl  {
  allow                   *
}
