version: 2
updates:
  - package-ecosystem: composer
    directory: /
    schedule: { interval: weekly }
    open-pull-requests-limit: 5
  - package-ecosystem: npm
    directory: /
    schedule: { interval: weekly }
    groups:
      npm-dev:
        dependency-type: development
  - package-ecosystem: github-actions
    directory: /
    schedule: { interval: weekly }
    groups:
      actions:
        patterns: ["*"]
  - package-ecosystem: docker
    directory: /docker/openlitespeed
    schedule: { interval: monthly }
