<?php

declare(strict_types=1);

namespace VehicleData\Core\Console;

use Illuminate\Console\Command;
use Illuminate\Support\Facades\File;
use VehicleData\Core\Importers\SourceRegistry;
use VehicleData\Core\Models\ImportRun;
use VehicleData\Core\Models\Source;
use VehicleData\Core\Reports\ExampleCoverage;
use VehicleData\Core\Support\AdmittedLicences;
use VehicleData\Core\Taxonomies\TaxonomyDefinitions;

/**
 * `vehicle:sources list` prints the registered sources; `vehicle:sources check` is the release
 * gate's licence check (exit 1 unless every source row has an admitted licence id, a licence URL
 * and an attribution, and every committed fixture file is named in `docs/data-sources.md`);
 * `vehicle:sources report` renders `docs/data-sources.md` (licences, attribution, last-run stats
 * and checksums straight from the `vd_sources`/`vd_import_runs` tables, the committed fixture
 * files with their SHA-256 and row counts, example coverage from `ExampleCoverage` and the
 * ordered normalisation and import rules - name normalisation from `NameNormaliser`'s own
 * docblock, plus identity resolution and the licence policy) so the committed documentation
 * can never drift from what the database and the importer actually do.
 */
final class SourcesCommand extends Command
{
    /** @var string */
    protected $signature = 'vehicle:sources {action : report|list|check} {--out=docs/data-sources.md} {--doc=docs/data-sources.md : the document `check` reads}';

    /** @var string */
    protected $description = 'List registered data sources, render docs/data-sources.md from them, or check licences and documented fixtures.';

    /** @deprecated use AdmittedLicences::IDS (kept for one release) */
    public const ADMITTED_LICENCES = AdmittedLicences::IDS;

    private const FIXTURE_DIR = __DIR__.'/../../database/fixtures';

    /**
     * How each source's committed fixture is produced by `scripts/fetch_fixtures.sh` (a
     * deterministic, script-generated selection) - kept here as the single place this text lives, not read back
     * out of the database, so the report can describe the *method* even though the DB only
     * ever records the *result* of running it.
     */
    private const FIXTURE_DESCRIPTIONS = [
        'eea' => 'Generated by `scripts/fetch_fixtures.sh` from the EEA CO2 monitoring dataset (RO, 2024): a deterministic per-make quota - '
            .'`ROW_NUMBER() OVER (PARTITION BY Mk ORDER BY Cn, Ft, ID)` capped at ≤ 13 rows per make, `MS=\'RO\'`, across the 15 fixed demo makes - '
            .'not a plain top-N cut, which a single alphabetically-dominant make would otherwise starve.',
        'ro-fleet' => 'Generated by `scripts/fetch_fixtures.sh` from the DRPCIV national fleet file: `CATEGORIE_NATIONALA=AUTOTURISM` rows only, '
            .'capped per make (≤ 13) across the same 15 makes the EEA fixture covers, taken in the source file\'s own (unsorted) order.',
        'wikidata' => 'Generated by `scripts/fetch_fixtures.sh` via a SPARQL query for a fixed list of manufacturer labels, `ORDER BY ?item` for '
            .'determinism, plus a Wikimedia Commons licence lookup for every referenced logo file.',
        'wmi' => 'Generated by `scripts/fetch_fixtures.sh` from NHTSA vPIC\'s GetWMIsForManufacturer, looked up for the fixed list of demo '
            .'manufacturer names (volkswagen, toyota, ford, hyundai, bmw, mercedes, kia, honda, tesla, renault).',
    ];

    /**
     * What "rows read" counts for each source, so the last-run numbers reconcile with the fixture
     * row counts listed under Fixtures (they are not the same unit for every source).
     */
    private const COUNT_NOTES = [
        'eea' => 'rows read = variant rows in the file.',
        'ro-fleet' => 'rows read = aggregated make and make/model totals built from the file\'s AUTOTURISM rows (one per distinct make plus one per distinct model), not the file\'s line count.',
        'wikidata' => 'rows read = distinct Wikidata items after merging the SPARQL bindings (one item can have several bindings, e.g. two logos or two inception dates).',
        'wmi' => 'rows read = WMI rows in the file; 6-character WMIs are rejected by design (`wmi_length`).',
    ];

    /** The ordered normalisation and import rules shown in docs/data-sources.md: most are documented on
     * NameNormaliser, but identity resolution (ADR 0007) and the licence policy (R12) are not - kept here,
     * not by reflection, so a rewording elsewhere doesn't silently break this string. */
    private const NORMALISATION_RULES = [
        'trim + collapse whitespace; empty → reject "empty"; placeholder tokens → reject "placeholder"; > 120 chars → reject "too_long"',
        'aliases (VW → Volkswagen, MERCEDES BENZ → Mercedes-Benz, SKODA → Škoda, CITROEN → Citroën, ROLLS ROYCE → Rolls-Royce)',
        'acronyms kept upper-case (BMW, DS, MG, SEAT, MINI, BYD, MAN, DAF, GMC, RAM, MCV, SW, TX, …)',
        'everything else Title Case; hyphenated parts title-cased separately',
        'models only: strip a trailing engine/drivetrain code (e.g. "2.0 TDI", "1.6 T-GDI", "XDRIVE30D"); ≥ 8 alphanumerics with digits and no space → reject "type_code"',
        'identity resolution (ADR 0007): a new slug that already belongs to another live record, or to another record\'s alias (any kind or record type), rejects the row "slug_collision"; a source reference over 120 characters rejects "ref_too_long". A rejected row is rolled back entirely (a per-row savepoint) and listed in the run\'s reject report.',
        'licence policy: a source whose licence id is not in the admitted list (CC-BY-4.0, OGL-ROU-1.0, CC0-1.0, US-PD) is refused before any write; `vehicle:sources check` repeats the check at release time.',
    ];

    public function handle(SourceRegistry $registry): int
    {
        return match ($this->argument('action')) {
            'list' => $this->list(),
            'report' => $this->report(),
            'check' => $this->check(),
            default => $this->unknownAction(),
        };
    }

    private function list(): int
    {
        $rows = Source::query()->orderBy('key')->get();
        $this->table(['key', 'name', 'licence', 'url'], $rows->map(fn (Source $s) => [$s->key, $s->name, $s->licence_id, $s->url])->all());

        return self::SUCCESS;
    }

    private function check(): int
    {
        $problems = [];
        $sources = Source::query()->orderBy('key')->get();
        if ($sources->isEmpty()) {
            $problems[] = 'no sources registered (run the seeders first)';
        }
        foreach ($sources as $source) {
            foreach (['licence_id' => 'licence id', 'licence_url' => 'licence URL', 'attribution' => 'attribution'] as $column => $label) {
                if (trim((string) $source->{$column}) === '') {
                    $problems[] = "{$source->key}: missing {$label}";
                }
            }
            if ((string) $source->licence_id !== '' && ! AdmittedLicences::admits((string) $source->licence_id)) {
                $problems[] = "{$source->key}: licence {$source->licence_id} is not admitted (".implode(', ', AdmittedLicences::IDS).')';
            }
        }

        $doc = $this->path((string) $this->option('doc'));
        $text = is_file($doc) ? (string) file_get_contents($doc) : '';
        if ($text === '') {
            $problems[] = "{$doc} is missing or empty";
        }
        $fixtures = self::fixtureFiles();
        foreach ($fixtures as $file) {
            if (! str_contains($text, basename($file))) {
                $problems[] = 'fixture '.basename($file)." is not named in {$doc}";
            }
        }

        if ($problems === []) {
            $this->info("Sources: {$sources->count()} with an admitted licence, licence URL and attribution; fixtures: ".count($fixtures).' named in the data-sources document.');

            return self::SUCCESS;
        }
        foreach ($problems as $problem) {
            $this->error($problem);
        }

        return self::FAILURE;
    }

    /** @return list<string> absolute paths of the committed fixture files, sorted */
    private static function fixtureFiles(): array
    {
        // Every data file, whatever its extension (dot-files such as .gitkeep and the Markdown licence
        // notice excluded): a fixture of a new format must not slip past the "documented" check just
        // because it isn't JSON or CSV.
        $files = array_values(array_filter(glob(self::FIXTURE_DIR.'/*') ?: [], static fn (string $f): bool => is_file($f) && ! str_ends_with($f, '.md')));
        sort($files);

        return $files;
    }

    /** Data rows in a fixture: the result list for JSON, non-empty lines after the header for CSV. */
    private static function fixtureRows(string $file): int
    {
        if (str_ends_with($file, '.csv')) {
            $lines = array_filter(explode("\n", (string) file_get_contents($file)), static fn (string $l): bool => trim($l) !== '');

            return max(0, count($lines) - 1);
        }
        $json = json_decode((string) file_get_contents($file), true);
        $rows = is_array($json) ? ($json['results'] ?? $json['sparql']['results']['bindings'] ?? []) : [];

        return is_array($rows) ? count($rows) : 0;
    }

    private function path(string $option): string
    {
        return str_starts_with($option, '/') || preg_match('/^[A-Za-z]:[\\\\\/]/', $option) === 1 ? $option : base_path($option);
    }

    private function report(): int
    {
        $path = $this->path((string) $this->option('out'));

        File::ensureDirectoryExists(dirname($path));
        File::put($path, $this->markdown());
        $this->info("Wrote {$path}");

        return self::SUCCESS;
    }

    private function markdown(): string
    {
        $md = "# Data sources\n\n";
        $md .= 'Generated by `php artisan vehicle:sources report` on '.now()->toDateString().". Every single-record response carries `sources[]` with these keys; list, CSV and snapshot responses carry the attributions in `X-Data-Attribution`.\n\n";
        $md .= 'API output is provided under the licences of the sources it comes from; no additional database right is claimed over the compilation. '
            .'Values are normalised on import (names, codes, units; see Normalisation rules), which is a change to the source data for attribution purposes. '
            ."The data is provided as is, without warranty of accuracy or completeness.\n";

        foreach (Source::query()->orderBy('key')->get() as $source) {
            $run = ImportRun::query()->where('source_id', $source->id)->where('status', 'succeeded')->orderByDesc('finished_at')->first();
            $md .= "\n## {$source->key}\n";
            $md .= "- **Name:** {$source->name}  - **Licence:** {$source->licence_id} - {$source->licence_name} ({$source->licence_url})  - **Attribution (required in every reuse):** {$source->attribution}\n";
            if (isset(self::FIXTURE_DESCRIPTIONS[$source->key])) {
                $md .= '- **Fixture:** '.self::FIXTURE_DESCRIPTIONS[$source->key]."\n";
            }
            if ($source->key === 'ro-fleet') {
                // OGL-ROU-1.0 carries a Romanian-language attribution string alongside the
                // English one stored on the source row (Licence::oglRou()->attributionRo);
                // both are required for a Romanian-facing reuse.
                $md .= '- **Attribution (RO):** Conține informații publice sub Licența Guvernamentală Deschisă v1.0'."\n";
            }
            $checksum = $run->file_checksum ?? 'not recorded for this source (see the fixture checksum under Fixtures)';
            $md .= '- **Dataset:** '.$source->url.'  - **Last successful import:** '.($run?->finished_at?->toIso8601String() ?? 'never')
                .'  - **Imported file checksum (SHA-256):** '.($run !== null ? $checksum : '-')
                .'  - **Rows read/written/rejected (last run):** '.($run !== null ? "{$run->rows_read}/{$run->rows_written}/{$run->rows_rejected}" : '-')
                .(isset(self::COUNT_NOTES[$source->key]) ? ' ('.self::COUNT_NOTES[$source->key].')' : '')."\n";
        }

        $md .= "\n## Fixtures\n";
        $md .= 'The only vehicle data committed to the repository: `packages/vehicle-data-core/database/fixtures/`, generated by `scripts/fetch_fixtures.sh` '
            ."and loaded by `ExampleDataSeeder` through the same import pipeline as a live run.\n\n";
        $md .= "| File | SHA-256 | Rows in the file |\n|---|---|---|\n";
        foreach (self::fixtureFiles() as $file) {
            $md .= '| '.basename($file).' | '.hash_file('sha256', $file).' | '.self::fixtureRows($file)." |\n";
        }

        $md .= "\n## Example coverage\n";
        $md .= "| Taxonomy | Term | Examples (two distinct makes where the fixtures allow) |\n|---|---|---|\n";
        $coverage = ExampleCoverage::compute();
        foreach (TaxonomyDefinitions::all() as $taxonomy => $def) {
            foreach ($def['terms'] as $code) {
                $examples = $coverage[$taxonomy][$code] ?? [];
                $cell = $examples === [] ? 'example: none' : implode('; ', array_map(fn (array $e) => "{$e['name']} ({$e['ref']})", $examples));
                $md .= "| {$taxonomy} | {$code} | {$cell} |\n";
            }
        }

        $md .= "\n## Known data issues\n";
        $md .= 'Source values are passed through unmodified apart from the normalisation rules below, so upstream errors reach the API as published. '
            .'Examples in these fixtures: some EEA rows carry an implausibly low `power_kw` for their engine (for example a 1199 cm³ petrol Dacia Duster at 12 kW), '
            .'and some commercial names already contain the make (a model named "Fiat 500" under the make Fiat). '
            ."Report suspected errors to the publisher; the API does not correct them by hand.\n";

        $md .= "\n## Normalisation rules\n";
        foreach (self::NORMALISATION_RULES as $i => $rule) {
            $md .= ($i + 1).". {$rule}\n";
        }

        $md .= "\n## Trademark notice\n";
        $md .= 'Manufacturer logos are referenced by Wikimedia Commons file name and licence only (public domain or CC BY without share-alike). '
            ."Logos remain trademarks of their owners; the reference does not imply endorsement.\n";

        return $md;
    }

    private function unknownAction(): int
    {
        $this->error('Unknown action; expected "report", "list" or "check".');

        return self::FAILURE;
    }
}
